database:
  username: ""
  password: ""
  host: "localhost"
  port: 3306
  db: "viptimer"
types:
  - type1
  - type2
  - type3
commands:
  give:
    - say %playername% is now vip!
  take:
    - say %playername% is now not a vip!