# 数据库相关配置
database:
  username: ""
  password: ""
  host: "localhost"
  port: 3306
  # 自行创建
  db: "viptimer"
# 可从 distributor 和 receiver 中选择
# 不填则为 none
# 具体解释请见 https://wiki.oases.red/VIP%E8%AE%A1%E6%97%B6%E6%8F%92%E4%BB%B6%E6%8A%80%E6%9C%AF%E6%96%87%E6%A1%A3
role: distributor
# 在获得/失去会员时显示的感谢信息。如不需要可留空。
thank-you-message: ~